[default.extend-words]

[files]
extend-exclude = [
  "CHANGELOG.md",
  "new-chat/chat_server/fixtures/*",
  "new-chat/chat_core/fixtures/*",
  "new-chat/notify_server/*.html",
  "chatapp/src/gen/messages_pb.ts"
]
